import type { Metadata } from "next";
import Script from "next/script";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./common/header";
import Footer from "./common/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Accountant AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Script
        id="gasiuf7et3y3eibie"
        strategy="beforeInteractive"
        dangerouslySetInnerHTML={{
          __html: `Script
        id="gasiuf7et3y3eibie"
        strategy="beforeInteractive"
        dangerouslySetInnerHTML={{__html: (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:3806906,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=')}
      />`,
        }}
      />
      {/* <body className={inter.className}> */}
      <body className="bg-white {inter.className}">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
